### ISSUE TITLE
"Manuel-du-démineur_1.pdf 	Mauvais PDF"

### ISSUE THREAD

**Issue by ozh** [gplaurin/keep-talking-and-nobody-explodes-manuel-francais#1]
Bonjour

D'abord, merci pour cette excellente et très fun traduction :)

Petit problème mineur: les gens qui ne connaissent pas GitHub et qui arrivent ici juste pour télécharger le PDF sont confus car ce qu'ils voient sur la page du repo est `Manuel-du-démineur_1.pdf      Mauvais PDF`, et du coup ils repartent en se disant "bah alors il est où le bon PDF?"

Donc, juste un petit commit sur le PDF, même inutile, pour changer ce message, serait le bienvenu :)

**Comment by gplaurin** [comment]
Fait!

**Comment by ozh** [comment]
:pizza: !
